name: neutrix-os-deployment

on: [ push ]

jobs:
  deploy:
    runs-on: ubuntu-latest
    steps:
      - uses: actions/checkout@v2
      - name: Log in with Azure
        uses: azure/login@v1
        with:
          creds: '${{ secrets.AZURE_CREDENTIALS }}'
      - name: Start the virtual machine
        uses: azure/CLI@v1
        with:
          azcliversion: 2.0.72
          inlineScript: |
              az vm  start -n deb2 --resource-group deb2_group
              export Ip_Address=$(az vm show -d -g deb2_group -n deb2 --query publicIps -o tsv)
              echo "HOST=$Ip_Address" >> $GITHUB_ENV
      - name: Wait till the virtual machine is up 
        run: |
          while [[ `az vm show -g deb2_group -n deb2 --show-details --query powerState` != "VM running" ]]; do
            sleep 5
            PS=`az vm show -g deb2_group -n deb2 --show-details --query powerState -o tsv | tr -d '"'`
            if [[ "${PS}" == "VM running" ]]; then
                echo "deb2 has started successfully..."
                echo "--------------------------------------------------"
                echo
                break
            else
                echo "$VM is still starting..."
            fi
          done
      - name: executing remote ssh commands using ssh key
        uses: appleboy/ssh-action@master
        with:
          host: ${{ env.HOST }}
          command_timeout: 200m
          username: ${{ secrets.USERNAME }}
          key: ${{ secrets.KEY }}
          port: ${{ secrets.PORT }}
          script: |
            su -l <<! >/dev/null 2>&1
            ${{ secrets.ROOT_PASS }}
            cd githubActions/NeutrixOs/
            git pull 
            ./buildNeutrixBuster.sh > /dev/tty
            !

  