name: neutrix-os-deployment

on: [ push ]

jobs:
  deploy:
    runs-on: ubuntu-latest
    steps:
      - uses: actions/checkout@v2
      - name: Log in with Azure
        uses: azure/login@v1
        with:
          creds: '${{ secrets.AZURE_CREDENTIALS }}'
      - name: Start the virtual machine
        uses: azure/CLI@v1
        with:
          azcliversion: 2.0.72
          inlineScript: |
              az vm  start -n neutrix-os --resource-group virtual-machines
              export Ip_Address=$(az vm show -d -g virtual-machines -n neutrix-os --query publicIps -o tsv)
              echo "HOST=$Ip_Address" >> $GITHUB_ENV
      - name: Wait till the virtual machine is up 
        run: |
          while [[ `az vm show -g virtual-machines -n neutrix-os --show-details --query powerState` != "VM running" ]]; do
            sleep 5
            PS=`az vm show -g virtual-machines -n neutrix-os --show-details --query powerState -o tsv | tr -d '"'`
            if [[ "${PS}" == "VM running" ]]; then
                echo "neutrix-os has started successfully..."
                echo "--------------------------------------------------"
                echo
                break
            else
                echo "$VM is still starting..."
            fi
          done
      - name: Configure SSH
        run: |
          mkdir -p ~/.ssh/
          echo "$SSH_KEY" > ~/.ssh/neutrix.key
          chmod 400 ~/.ssh/neutrix.key
          cat >>~/.ssh/config <<END
          Host neutrix
            HostName $SSH_HOST
            User $SSH_USER
            IdentityFile ~/.ssh/neutrix.key
            StrictHostKeyChecking no
          END
          chmod 400 ~/.ssh/config
        env:
          SSH_USER: ${{ secrets.USERNAME }}
          SSH_KEY: ${{ secrets.KEY }}
          SSH_HOST: ${{ env.HOST }}
      - name: executing remote ssh commands using ssh key
        run: |
          cat ~/.ssh/config
          ssh  neutrix "whoami"
    
  