name: neutrix-os-deployment

on: [ push ]

jobs:
  deploy:
    runs-on: ubuntu-latest
    steps:
      - uses: actions/checkout@v2
      - name: Log in with Azure
        uses: azure/login@v1
        with:
          creds: '${{ secrets.AZURE_CREDENTIALS }}'
      - name: Start the virtual machine
        uses: azure/CLI@v1
        with:
          azcliversion: 2.0.72
          inlineScript: |
              az vm  start -n neutrix-os --resource-group virtual-machines
              export Ip_Address=$(az vm show -d -g virtual-machines -n neutrix-os --query publicIps -o tsv)
              echo "ip_address=$Ip_Address" >> $GITHUB_ENV
      - name: Wait till the virtual machine is up 
        run: |
          while [[ `az vm show -g virtual-machines -n neutrix-os --show-details --query powerState` != "VM running" ]]; do
            sleep 5
            PS=`az vm show -g virtual-machines -n neutrix-os --show-details --query powerState -o tsv | tr -d '"'`
            if [[ "${PS}" == "VM running" ]]; then
                echo "neutrix-os has started successfully..."
                echo "--------------------------------------------------"
                echo
                break
            else
                echo "$VM is still starting..."
            fi
          done
      - name: Tesing env variable 
        run: echo "${{ env.ip_address }}"
      - name: executing remote ssh commands using ssh key
        uses: appleboy/ssh-action@master
        with:
          host: ${{ secrets.HOST }}
          username: ${{ secrets.USERNAME }}
          key: ${{ secrets.KEY }}
          port: ${{ secrets.PORT }}
          script: whoami
      
      
      - name: Stop the virtual machine
        uses: azure/CLI@v1
        with:
          azcliversion: 2.0.72
          inlineScript: |
              az vm stop -n neutrix-os --resource-group virtual-machines
              rm ip_address.txt
    
  