name: neutrix-os-deployment

on: [ push ]

jobs:
  deploy:
    runs-on: ubuntu-latest
    steps:
      - uses: actions/checkout@v2
      - name: Log in with Azure
        uses: azure/login@v1
        with:
          creds: '${{ secrets.AZURE_CREDENTIALS }}'
      - name: Start the virtual machine
        uses: azure/CLI@v1
        with:
          azcliversion: 2.0.72
          inlineScript: |
              az vm  start -n neutrix-os --resource-group virtual-machines
              az vm list-ip-addresses -g virtual-machines -n neutrix-os
    
  